set positional-arguments
alias s := scripts

# default recipe to display help information
default:
  @just --list

# Installs the opt8n binary
install-opt8n:
  cargo install --path ../../bin/opt8n --locked

# Cleans build artifacts and cache
clean:
  @forge clean

# Runs all scripts
scripts: weth9 

# Runs the weth9 precompile script
weth9:
  forge script Weth9Precompile

# Generates all execution test fixtures for scripts in this project
gen: gen-weth9

# Generates the execution test fixture for the weth9 precompile script
gen-weth9: install-opt8n clean
  opt8n --output ./examples/execution/Weth9Precompile.json script Weth9Precompile
